-- 000: create the Membership database. Idempotent.
SET NOCOUNT ON;
IF DB_ID('Cobble398') IS NULL
    CREATE DATABASE Cobble398;
GO
ALTER DATABASE Cobble398 SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO
